
framework:
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\NativeFileSessionHandler
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
